# This file was generated by GoReleaser. DO NOT EDIT.
cask "meta-ads-cli" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "8598145c271d7a333932695a336e0b8c44a163cbb193d974393e2f168f477cfc"
      url "https://github.com/KudcraftsHQ/meta-ads-cli/releases/download/v#{version}/meta-ads-cli-#{version}-macos-amd64.tar.gz",
        verified: "github.com/KudcraftsHQ/meta-ads-cli/"
    end
    on_arm do
      sha256 "06ff631fc8385aab754910ee932f40682d0bd9ff9c6e641032b9fd59a5dbe62b"
      url "https://github.com/KudcraftsHQ/meta-ads-cli/releases/download/v#{version}/meta-ads-cli-#{version}-macos-arm64.tar.gz",
        verified: "github.com/KudcraftsHQ/meta-ads-cli/"
    end
  end

  on_linux do
    on_intel do
      sha256 "468a2b4671ddd724ac24880c9a46d83122570e7fb5c454b96d9b8fb7f4a82337"
      url "https://github.com/KudcraftsHQ/meta-ads-cli/releases/download/v#{version}/meta-ads-cli-#{version}-linux-amd64.tar.gz",
        verified: "github.com/KudcraftsHQ/meta-ads-cli/"
    end
    on_arm do
      sha256 "277469bdeee47381cba03f9d1141e3cfff144a5b98af31a2eb49856b0b349fa4"
      url "https://github.com/KudcraftsHQ/meta-ads-cli/releases/download/v#{version}/meta-ads-cli-#{version}-linux-arm64.tar.gz",
        verified: "github.com/KudcraftsHQ/meta-ads-cli/"
    end
  end

  name "meta-ads-cli"
  desc "A command line interface to the Meta Marketing API"
  homepage "https://github.com/KudcraftsHQ/meta-ads-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "meta-ads"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/meta-ads"]
    end
  end
  generate_completions_from_executable "meta-ads", "completion",
    base_name: "meta-ads",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required

end
